--Creating provisional tables

CREATE TABLE matches (
	match_date DATE PRIMARY KEY,
	home_team VARCHAR,
	away_team VARCHAR,
	home_team_continent VARCHAR,
	away_team_continent VARCHAR,
	home_team_fifa_rank INT,
	away_team_fifa_rank INT,
	home_team_total_fifa_points INT,
	away_team_total_fifa_points INT,
	home_team_score INT,
	away_team_score INT,
	tournament VARCHAR,
	city VARCHAR,
	country VARCHAR,
	neutral_location BOOL,
	shoot_out VARCHAR,
	home_team_result INT,
	home_team_golakeeper_score INT,
	away_team_goalkeeper_score INT,
	home_team_mean_defense_score INT,
	home_team_mean_offense_score INT,
	home_team_mean_midfield_score INT,
	away_team_mean_defense_score INT,
	away_team_mean_offense_score INT,
	away_team_mean_midfield_score INT);
	
CREATE TABLE players (
	sofifa_id int PRIMARY KEY,
	player_url varchar,
	short_name varchar,
	long_name varchar,
	player_positions varchar,
	overall int,
	potential int,
	value_eur int,
	wage_eur int,
	age int,
	dob date,
	height_cm int,
	weight_kg int,
	club_team_id int,
	club_name varchar,
	league_name varchar,
	league_level int,
	club_position varchar,
	club_jersey_number int,
	club_loaned_from varchar,
	club_joined date,
	club_contract_valid_until int,
	nationality_id int,
	nationality_name varchar,
	nation_team_id int,
	nation_position varchar,
	nation_jersey_number int,
	preferred_foot varchar,
	weak_foot int,
	skill_moves int,
	international_reputation int,
	work_rate varchar,
	body_type varchar,
	release_clause_eur int,
	player_tags varchar,
	player_traits varchar,
	pace int,
	shooting int,
	pass int,
	dribbling int,
	defending int);
	
CREATE TABLE teams (
	nation_team_id int PRIMARY KEY,
	nation_team_name varchar
	);